In [ ]:
import sklearn
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import datasets

In [ ]:
cancer = datasets.load_breast_cancer()

In [ ]:
print("Features: ", cancer.feature_names)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [ ]:
print("Labels: ", cancer.target_names)

Labels:  ['malignant' 'benign']


In [ ]:
x = cancer.data  # All of the features
y = cancer.target  # All of the labels

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.2)

In [ ]:
print(x_train[:5], y_train[:5])

[[1.359e+01 1.784e+01 8.624e+01 5.723e+02 7.948e-02 4.052e-02 1.997e-02
  1.238e-02 1.573e-01 5.520e-02 2.580e-01 1.166e+00 1.683e+00 2.222e+01
  3.741e-03 5.274e-03 1.065e-02 5.044e-03 1.344e-02 1.126e-03 1.550e+01
  2.610e+01 9.891e+01 7.391e+02 1.050e-01 7.622e-02 1.060e-01 5.185e-02
  2.335e-01 6.263e-02]
 [1.727e+01 2.542e+01 1.124e+02 9.288e+02 8.331e-02 1.109e-01 1.204e-01
  5.736e-02 1.467e-01 5.407e-02 5.100e-01 1.679e+00 3.283e+00 5.838e+01
  8.109e-03 4.308e-02 4.942e-02 1.742e-02 1.594e-02 3.739e-03 2.038e+01
  3.546e+01 1.328e+02 1.284e+03 1.436e-01 4.122e-01 5.036e-01 1.739e-01
  2.500e-01 7.944e-02]
 [1.146e+01 1.816e+01 7.359e+01 4.031e+02 8.853e-02 7.694e-02 3.344e-02
  1.502e-02 1.411e-01 6.243e-02 3.278e-01 1.059e+00 2.475e+00 2.293e+01
  6.652e-03 2.652e-02 2.221e-02 7.807e-03 1.894e-02 3.411e-03 1.268e+01
  2.161e+01 8.269e+01 4.898e+02 1.144e-01 1.789e-01 1.226e-01 5.509e-02
  2.208e-01 7.638e-02]
 [2.018e+01 2.397e+01 1.437e+02 1.245e+03 1.286e-01 3.454e-01 3.754

In [ ]:
import sklearn
from sklearn import datasets
from sklearn import svm

cancer = datasets.load_breast_cancer()

print(cancer.feature_names)
print(cancer.target_names)

x = cancer.data
y = cancer.target

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.2)

print(x_train, y_train)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']
[[2.110e+01 2.052e+01 1.381e+02 ... 2.280e-01 2.268e-01 7.425e-02]
 [1.706e+01 2.100e+01 1.118e+02 ... 1.827e-01 2.623e-01 7.599e-02]
 [1.018e+01 1.753e+01 6.512e+01 ... 5.575e-02 3.055e-01 8.797e-02]
 ...
 [1.082e+01 2.421e+01 6.889e+01 ... 3.264e-02 3.059e-01 7.626e-02]
 [1.243e+01 1.700e+01 7.860e+01 ... 2.832e-02 1.901e-01 5.932e-02]
 [1.678e+01 1.880e+01 1.093e+02 ... 1.474e-01 2.810e-01 7.228e-02]] [0 0 1 1 0 0 1

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
predictions = logmodel.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.97      0.84      0.90        45
           1       0.91      0.99      0.94        69

    accuracy                           0.93       114
   macro avg       0.94      0.91      0.92       114
weighted avg       0.93      0.93      0.93       114



In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_model = SVC()

In [ ]:
svc_model.fit(x_train,y_train)

SVC()

In [ ]:
predictions = svc_model.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(confusion_matrix(y_test,predictions))

[[35 10]
 [ 0 69]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.78      0.88        45
           1       0.87      1.00      0.93        69

    accuracy                           0.91       114
   macro avg       0.94      0.89      0.90       114
weighted avg       0.92      0.91      0.91       114

